/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Moderator;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ModeratorRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author murta
 */
public class ModeratorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModeratorWorkAreaJPanel
     */
    private JPanel leftContainer;
    private JPanel rightContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private Ecosystem system;
    private ModeratorRequest request;

    public ModeratorWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount account, Ecosystem system) {
        initComponents();
        this.leftContainer = leftContainer;
        this.rightContainer = rightContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.system = system;
        
        if (account.getBankAccount().getName() == null) {
            btnCreateBankAccount.setVisible(true);
            btnLoanApproval.setVisible(false);
            manageRequestBtn.setVisible(false);
        } else {
            btnCreateBankAccount.setVisible(false);
            btnLoanApproval.setVisible(true);

            manageRequestBtn.setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageRequestBtn = new javax.swing.JButton();
        btnLoanApproval = new javax.swing.JButton();
        btnCreateBankAccount = new javax.swing.JButton();

        jLabel1.setText("Moderator Work Area");

        manageRequestBtn.setText("Manage Request");
        manageRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestBtnActionPerformed(evt);
            }
        });

        btnLoanApproval.setText("Bank notifications");
        btnLoanApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanApprovalActionPerformed(evt);
            }
        });

        btnCreateBankAccount.setText("Create Bank Account");
        btnCreateBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(440, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoanApproval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(447, 447, 447))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(btnCreateBankAccount)
                .addGap(31, 31, 31)
                .addComponent(manageRequestBtn)
                .addGap(35, 35, 35)
                .addComponent(btnLoanApproval)
                .addContainerGap(682, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestBtnActionPerformed
        // TODO add your handling code here:
        ManageRequestJPanel donateFundsJPanel = new ManageRequestJPanel(rightContainer, enterprise, account, system);
        rightContainer.add("DonateFundsJPanel", donateFundsJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_manageRequestBtnActionPerformed

    private void btnLoanApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanApprovalActionPerformed
        // TODO add your handling code here:


        BankNotifications loanApprovalJPanel = new BankNotifications (rightContainer, enterprise, account, system);
        rightContainer.add("LoanApprovalJPanel",  loanApprovalJPanel);


        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);

    }//GEN-LAST:event_btnLoanApprovalActionPerformed

    private void btnCreateBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAccountActionPerformed
        // TODO add your handling code here:
        ModeratorCreateBankAccountJPanel moderatorCreateBankAccountJPanel = new ModeratorCreateBankAccountJPanel(leftContainer, rightContainer, enterprise, account, system);
        rightContainer.add("LenderCreateBankAccountJPanel", moderatorCreateBankAccountJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnCreateBankAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAccount;
    private javax.swing.JButton btnLoanApproval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageRequestBtn;
    // End of variables declaration//GEN-END:variables
}
