/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harsh $hinde
 */
public class GovernmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentWorkAreaJPanel
     */
   
    private JPanel rightContainer;
    private JPanel leftContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem system;

    public GovernmentWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount account, Ecosystem business) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.rightContainer= rightContainer;
        this.leftContainer=leftContainer;
        this.userAccount = account;
       
        this.enterprise = enterprise;
        this.system=system;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOrganizationDetails = new javax.swing.JButton();
        btnFinancials = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Government Work Area");

        btnOrganizationDetails.setText("View Organization Details");
        btnOrganizationDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizationDetailsActionPerformed(evt);
            }
        });

        btnFinancials.setText("View Financials Details");
        btnFinancials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOrganizationDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinancials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(btnOrganizationDetails)
                .addGap(59, 59, 59)
                .addComponent(btnFinancials)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganizationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizationDetailsActionPerformed
        // TODO add your handling code here:
        OrganizationDetailsJPanel Opanel=new OrganizationDetailsJPanel(rightContainer,enterprise,userAccount,system);
        rightContainer.add("OrganizationDetailsJPanel",Opanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnOrganizationDetailsActionPerformed

    private void btnFinancialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialsActionPerformed
        // TODO add your handling code here:
        ViewFinancialsJPanel viewFinancialsJPanel = new ViewFinancialsJPanel(rightContainer,enterprise,userAccount,system);
        rightContainer.add("ViewFinancialsJPanel",viewFinancialsJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnFinancialsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinancials;
    private javax.swing.JButton btnOrganizationDetails;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
