/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Government;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.BankOrganisation;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.LenderOrganisation;
import Business.Organisation.ModeratorOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harsh $hinde
 */
public class OrganizationDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganizationDetailsJPanel
     */
    private JPanel rightContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Ecosystem system;

    OrganizationDetailsJPanel(JPanel rightContainer, Enterprise enterprise, UserAccount userAccount, Ecosystem system) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.rightContainer=rightContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.system=system;
        
        populateCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOrganizationDetails = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        btnView = new javax.swing.JButton();

        cmbOrganizationDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganizationDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationDetailsActionPerformed(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "SSN", "Reputation Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMember);
        if (tblMember.getColumnModel().getColumnCount() > 0) {
            tblMember.getColumnModel().getColumn(2).setHeaderValue("Reputation Score");
        }

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnView)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(cmbOrganizationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cmbOrganizationDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateCombo(){
    
        cmbOrganizationDetails.removeAllItems();
        
        for (Organisation organisation : enterprise.getOrganisationDirectory().getOrganisationList()){
            if(organisation instanceof BorrowerOrganisation || organisation instanceof LenderOrganisation || 
               organisation instanceof ModeratorOrganisation || organisation instanceof BankOrganisation)
            cmbOrganizationDetails.addItem(organisation);
        }
    }
    
    
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMember.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        Employee e=(Employee)tblMember.getValueAt(selectedRow, 0);
        
        ViewJPanel Vpanel=new ViewJPanel(rightContainer,enterprise,userAccount,system,e);
        rightContainer.add("ViewJPanel",Vpanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);    
    }//GEN-LAST:event_btnViewActionPerformed

    private void cmbOrganizationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationDetailsActionPerformed
        // TODO add your handling code here:
        Organisation organisation = (Organisation) cmbOrganizationDetails.getSelectedItem();
        if (organisation != null){
            populateTable(organisation);
        }
    }//GEN-LAST:event_cmbOrganizationDetailsActionPerformed

    private void populateTable(Organisation organisation){
        DefaultTableModel model = (DefaultTableModel) tblMember.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee: organisation.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee;
            row[1] = employee.getSsn();
           // row[2] = reputation score here;
            
            model.addRow(row);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox cmbOrganizationDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMember;
    // End of variables declaration//GEN-END:variables
}
