/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.BankOrganisation;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.LenderOrganisation;
import Business.Organisation.ModeratorOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BorrowerLoanRepayRequest;
import Business.WorkQueue.ModeratorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harsh $hinde
 */
public class BankWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankWorkAreaJPanel
     *
     *
     */
    private JPanel rightContainer;
    private JPanel leftContainer;
    private UserAccount userAccount;
//    private BankAccount bankAccount;
    private LenderOrganisation lenderOrganisation;
    private Enterprise enterprise;
    private Ecosystem system;
    private BankOrganisation bankOrganisation;
    private  WorkRequest bRequest;

    public BankWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount account, Ecosystem system) {
        initComponents();
        this.rightContainer = rightContainer;
        this.leftContainer = leftContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.system = system;//To change body of generated methods, choose Tools | Templates.

        
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCheckRequests = new javax.swing.JButton();
        btnRepayBank = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Banker Work Area");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 53, 216, -1));

        btnCheckRequests.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCheckRequests.setText("Check Requests");
        btnCheckRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckRequestsActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, -1));

        btnRepayBank.setText("Borrower Repayment Requests");
        btnRepayBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepayBankActionPerformed(evt);
            }
        });
        jPanel1.add(btnRepayBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckRequestsActionPerformed
        // TODO add your handling code here:
        ModeratorRequestJPanel Moderatorpanel = new ModeratorRequestJPanel(rightContainer, enterprise, userAccount, system);
        rightContainer.add("CheckAppointmentJPanel", Moderatorpanel);
        CardLayout cardLayout = (CardLayout) rightContainer.getLayout();
        cardLayout.next(rightContainer);

    }//GEN-LAST:event_btnCheckRequestsActionPerformed

    private void btnRepayBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepayBankActionPerformed
        // TODO add your handling code here:

        ModeratorRequest request;
        BorrowerRepayRequests borrowerRepayRequests = new BorrowerRepayRequests(rightContainer, enterprise, userAccount, system);
        rightContainer.add("BorrowerRepayRequests", borrowerRepayRequests);
        CardLayout cardLayout = (CardLayout) rightContainer.getLayout();
        cardLayout.next(rightContainer);
    }//GEN-LAST:event_btnRepayBankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckRequests;
    private javax.swing.JButton btnRepayBank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
