/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank;

import Business.BankAccount.BankAccount;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.BankOrganisation;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.LenderOrganisation;
import Business.Organisation.ModeratorOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BorrowerLoanRepayRequest;
import Business.WorkQueue.ModeratorRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manas
 */
public class BorrowerRepayRequests extends javax.swing.JPanel {

    /**
     * Creates new form BorrowerRepayRequests
     */
    private JPanel rightContainer;
    private JPanel leftContainer;
    private UserAccount userAccount;
//    private BankAccount bankAccount;
    private ModeratorOrganisation moderatorOrganisation;
    private Enterprise enterprise;
    private Ecosystem system;
    private BankOrganisation bankOrganisation;
    private ModeratorRequest modRequest;

    BorrowerRepayRequests(JPanel rightContainer, Enterprise enterprise, UserAccount userAccount, Ecosystem system) {
      initComponents(); 
       this.rightContainer = rightContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
       
        this.system = system;//To change body of generated methods, choose Tools | Templates.
        
        populateTable();
        populateTable2();
        
    }
    
    public void populateTable(){
     Organisation org = null;
            for (Organisation organisation : enterprise.getOrganisationDirectory().getOrganisationList()){
            if (organisation instanceof ModeratorOrganisation){
                org = organisation;
                break;
            }
        }
        if (org!=null){
            DefaultTableModel model = (DefaultTableModel) tableRepay.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            if(request instanceof ModeratorRequest){
            Object[] row = new Object[2];
            row[0] = request;
            row[1] = ((ModeratorRequest) request).getRepayAmount();
//            row[2] =  ((BorrowerLoanRepayRequest) request).getLenderName();
//            row[3] =((BorrowerLoanRepayRequest) request).getRemainingAmont();
             
            
//                System.out.println("UserInterface.Bank.BorrowerRepayRequests.populateTable()"+((BorrowerLoanRepayRequest) request).getLenderName());
            
            model.addRow(row);
        }
        }
        }
    
    
    
    
    }

     public void populateTable2(){
     Organisation org = null;
            for (Organisation organisation : enterprise.getOrganisationDirectory().getOrganisationList()){
            if (organisation instanceof ModeratorOrganisation){
                org = organisation;
                break;
            }
        }
        if (org!=null){
            DefaultTableModel model = (DefaultTableModel) tblsecond.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            if(request instanceof ModeratorRequest){
            Object[] row = new Object[4];
            row[0] =((ModeratorRequest) request).getLender1();
            row[1] =  request;
            row[2] = ((ModeratorRequest) request).getPendingAmount();
            row[3] = ((ModeratorRequest) request).getRepayAmount();
//            row[2] =  ((BorrowerLoanRepayRequest) request).getLenderName();
//            row[3] =((BorrowerLoanRepayRequest) request).getRemainingAmont();
             
            
//                System.out.println("UserInterface.Bank.BorrowerRepayRequests.populateTable()"+((BorrowerLoanRepayRequest) request).getLenderName());
            
            model.addRow(row);
        }
        }
        }
    
        
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRepay = new javax.swing.JTable();
        btnCredit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsecond = new javax.swing.JTable();
        btnSend = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Repay Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 873, 37));

        tableRepay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower", "RepayAmount"
            }
        ));
        jScrollPane1.setViewportView(tableRepay);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 873, 126));

        btnCredit.setText("Money to credit Lender");
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        add(btnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 529, 186, -1));

        tblsecond.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lender", "Borrower", "Pending Amount", "Repay Amount"
            }
        ));
        jScrollPane2.setViewportView(tblsecond);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 873, 126));

        btnSend.setText("Send Notification to Moderator");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 249, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblsecond.getSelectedRow();

        if (selectedRow < 0){
            
            JOptionPane.showMessageDialog(null,"Please select a row","Warning",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ModeratorRequest request = (ModeratorRequest)tblsecond.getValueAt(selectedRow, 1);
        int pendingAmount = (request.getLoanAmount()) - request.getRepayAmount();
        request.setPendingAmount(pendingAmount);
        float balance = request.getLender1().getBankAccount().getBankBalance();
        request.getLender1().getBankAccount().setBankBalance(balance + (request.getRepayAmount()));
        float modBalance = request.getReceiver().getBankAccount().getBankBalance();
        request.getReceiver().getBankAccount().setBankBalance(modBalance - pendingAmount);
        
        System.out.println(request.getReceiver().getBankAccount().getBankBalance());
        System.out.println(request.getLender1().getBankAccount().getBankBalance());

            
            
        

    }//GEN-LAST:event_btnCreditActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Message sent to Moderator");
        
        
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableRepay;
    private javax.swing.JTable tblsecond;
    // End of variables declaration//GEN-END:variables
}
