/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organisation.BankOrganisation;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankerWorkRequest;
import Business.WorkQueue.ModeratorRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manas
 */
public class BorrowerAcknowldgementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BorrowerAcknowldgementJPanel
     */
     private JPanel leftContainer;
    private JPanel rightContainer;
    private Enterprise enterprise;
    private UserAccount userAccount ;
    private Ecosystem system;
    private BankOrganisation bankOrganisation;
    private ModeratorRequest request;

    BorrowerAcknowldgementJPanel(JPanel rightContainer, Enterprise enterprise, UserAccount userAccount, Ecosystem system, ModeratorRequest  request) {
       
        initComponents(); 
//        this.leftContainer = leftContainer;
        this.rightContainer = rightContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.request=request;
        this.system = system;//To change body of generated methods, choose Tools | Templates.
//        populateComboBox();
        txtLenderBankBalance.setText(String.valueOf(request.getLender1().getBankAccount().getBankBalance()));
        txtborrowerBankBalance.setText(String.valueOf(request.getSender().getBankAccount().getBankBalance()));
    }

    
    
    
    
//     private void populateComboBox() {
//
//        ComboBoxBorrowers.removeAllItems();
//        Organisation org = null;
//        for (Organisation organization : enterprise.getOrganisationDirectory().getOrganisationList()) {
//            if (organization instanceof BorrowerOrganisation) {
//                org = organization;
//                break;
//            }
//        }
//        if (org != null) {
//
//            for (Employee emp : org.getEmployeeDirectory().getEmployeeList()) {
////                 String borrowerName=emp.getName();
//                ComboBoxBorrowers.addItem(emp);
//
//            }
//        }
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        txtLenderBankBalance = new javax.swing.JTextField();
        txtborrowerBankBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtLenderBankBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 110, -1));
        add(txtborrowerBankBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        jLabel1.setText("lender");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel2.setText("borrower");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField txtLenderBankBalance;
    private javax.swing.JTextField txtborrowerBankBalance;
    // End of variables declaration//GEN-END:variables
}
