/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Organisation.Organisation;
import javax.swing.JPanel;
import Business.Organisation.OrganisationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Harsh $hinde
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeJPanel
     */
    private OrganisationDirectory organisationDirectory;
    private Organisation organisation;
    private JPanel rightContainer;
    private EmployeeDirectory employeeDirectory;

    ManageEmployeeJPanel(JPanel rightContainer, OrganisationDirectory organisationDirectory, EmployeeDirectory employeeDirectory, Organisation organisation) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.rightContainer = rightContainer;
        this.organisationDirectory =organisationDirectory;
        this.organisation = organisation;
        this.employeeDirectory = employeeDirectory;       
        populateOrganisationComboBox();
        populateOrganisationEmpComboBox();
    }

    
    public void populateOrganisationComboBox(){
        orgDeptCmb.removeAllItems();
        
        for (Organisation organisation : organisationDirectory.getOrganisationList()){
            orgDeptCmb.addItem(organisation);
        }
    }
    
     public void populateOrganisationEmpComboBox(){
        orgCmb.removeAllItems();
        
        for (Organisation organisation : organisationDirectory.getOrganisationList()){
            orgCmb.addItem(organisation);
        }
    }
     
     private void populateTable(Organisation organisation){
        DefaultTableModel model = (DefaultTableModel) organisationJTable.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organisation.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee;
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organisationJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orgDeptCmb = new javax.swing.JComboBox();
        orgCmb = new javax.swing.JComboBox();
        NameJTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        createEmployeeBtn = new javax.swing.JButton();
        deleteEmployeeBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();

        jLabel1.setText("Organization Department:");

        organisationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organisationJTable);

        jLabel2.setText("Name");

        jLabel3.setText("Organization");

        orgDeptCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgDeptCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgDeptCmbActionPerformed(evt);
            }
        });

        orgCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        createEmployeeBtn.setText("Create Employee");
        createEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeBtnActionPerformed(evt);
            }
        });

        deleteEmployeeBtn.setText("Delete Employee");
        deleteEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Description");

        jLabel5.setText("SSN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(27, 27, 27)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orgCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameJTextField)
                            .addComponent(descriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(ssnTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(orgDeptCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orgDeptCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(orgCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployeeBtn)
                    .addComponent(backBtn))
                .addGap(31, 31, 31)
                .addComponent(deleteEmployeeBtn)
                .addContainerGap(409, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeBtnActionPerformed
        // TODO add your handling code here:
        Organisation organisation = (Organisation) orgCmb.getSelectedItem();
        
        String name = NameJTextField.getText();
        String desc= descriptionText.getText();
        
        int ssn = 0;
       if(name.trim().isEmpty() || desc.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill up employee details!!");
            return;
        }
       try{
           ssn = Integer.parseInt(ssnTextField.getText());
       }
       
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Please fill up SSN in numeric values!!");
           return;
       }
       
       
   
       
        organisation.getEmployeeDirectory().createEmployee(name,desc,ssn);
    
        
        populateTable(organisation);
    }//GEN-LAST:event_createEmployeeBtnActionPerformed

    private void orgDeptCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgDeptCmbActionPerformed
        // TODO add your handling code here:
        Organisation organisation = (Organisation) orgDeptCmb.getSelectedItem();
        if (organisation != null){
            populateTable(organisation);
        }
    }//GEN-LAST:event_orgDeptCmbActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightContainer.remove(this);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeBtnActionPerformed
        // TODO add your handling code here:
//         int selectedRow=organisationJTable.getSelectedRow();
//          if(selectedRow>=0){
//          int dialogButton=JOptionPane.YES_NO_OPTION;
//          int dialogResult=JOptionPane.showConfirmDialog(null,"Would you like to delete the account Detials?", "Warning", dialogButton);
//          if(dialogResult==JOptionPane.YES_OPTION){
//          
//          
//          Employee employee=(Employee)organisationJTable.getValueAt(selectedRow,1);
//          EmployeeDirectory empDir = organisation.getEmployeeDirectory();
//          empDir.deleteEmployee(employee);
//          populateTable(organisation);
//          
//          }
//        }
//        
//        else 
//            JOptionPane.showMessageDialog(null,"Select a row from table","Warning",JOptionPane.WARNING_MESSAGE);
//        
//        
    }//GEN-LAST:event_deleteEmployeeBtnActionPerformed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameJTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createEmployeeBtn;
    private javax.swing.JButton deleteEmployeeBtn;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgCmb;
    private javax.swing.JComboBox orgDeptCmb;
    private javax.swing.JTable organisationJTable;
    private javax.swing.JTextField ssnTextField;
    // End of variables declaration//GEN-END:variables
}
