/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.Ecosystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Harsh $hinde
 */
public class BusinessIntelligenceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessIntelligenceJPanel
     */
    
    private JPanel rightContainer;
    private Ecosystem system;
    public BusinessIntelligenceJPanel(JPanel rightContainer, Ecosystem system) {
        initComponents();
        
        this.rightContainer=rightContainer;
        this.system=system;
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLenderDetails = new javax.swing.JButton();
        btnBorrowerDetails = new javax.swing.JButton();
        btnBorrowerRequestDetails = new javax.swing.JButton();

        btnLenderDetails.setText("Show Lender Donation Details");
        btnLenderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenderDetailsActionPerformed(evt);
            }
        });

        btnBorrowerDetails.setText("Show Employee Count");
        btnBorrowerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowerDetailsActionPerformed(evt);
            }
        });

        btnBorrowerRequestDetails.setText("Show Borrower Request Details");
        btnBorrowerRequestDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowerRequestDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLenderDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrowerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrowerRequestDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnLenderDetails)
                .addGap(18, 18, 18)
                .addComponent(btnBorrowerDetails)
                .addGap(18, 18, 18)
                .addComponent(btnBorrowerRequestDetails)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrowerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowerDetailsActionPerformed
        // TODO add your handling code here:
        BorrowerDetailsJPanel panel = new BorrowerDetailsJPanel(rightContainer, system);
        rightContainer.add("BorrowerDetailsJPanel", panel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnBorrowerDetailsActionPerformed

    private void btnLenderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenderDetailsActionPerformed
        // TODO add your handling code here:
        TopLenderDetailsJPanel panel = new TopLenderDetailsJPanel(rightContainer, system);
        rightContainer.add("BorrowerDetailsJPanel", panel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnLenderDetailsActionPerformed

    private void btnBorrowerRequestDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowerRequestDetailsActionPerformed
        // TODO add your handling code here:
        TopBorrowerRequestJPanel panel = new TopBorrowerRequestJPanel(rightContainer, system);
        rightContainer.add("TopBorrowerRequestDetailsJPanel", panel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnBorrowerRequestDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowerDetails;
    private javax.swing.JButton btnBorrowerRequestDetails;
    private javax.swing.JButton btnLenderDetails;
    // End of variables declaration//GEN-END:variables
}
