/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Lender;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.BorrowerOrganisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author murta
 */
public class LenderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LenderWorkAreaJPanel
     */
    private JPanel leftContainer;
    private JPanel rightContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ecosystem system;
//    private BorrowerOrganisation borrowerOrganisation;
    
    public LenderWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount userAccount, Ecosystem system) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        this.leftContainer = leftContainer;
        this.rightContainer = rightContainer;
        this.userAccount = userAccount;
//        this.borrowerOrganisation =borrowerOrganisation;
        
        if(userAccount.getBankAccount().getName() == null){
            btnCreateBankAccount.setVisible(true);
            btnLenderFunctions.setVisible(false);
                
        }
        else{
            btnCreateBankAccount.setVisible(false);
            btnLenderFunctions.setVisible(true);
                 
        }      
    }

//    public LenderWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount userAccount, Ecosystem business) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLenderFunctions = new javax.swing.JButton();
        btnCreateBankAccount = new javax.swing.JButton();

        jLabel1.setText("    Lender Work Area ");

        btnLenderFunctions.setText("Lender Functions");
        btnLenderFunctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenderFunctionsActionPerformed(evt);
            }
        });

        btnCreateBankAccount.setText("Create Bank Account");
        btnCreateBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateBankAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(btnLenderFunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(748, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnCreateBankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnLenderFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(662, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLenderFunctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenderFunctionsActionPerformed
        // TODO add your handling code here:
        LenderFuntionsJPanel lenderFuntionsJPanel = new LenderFuntionsJPanel(rightContainer, enterprise, userAccount, system);
        rightContainer.add("LenderFuntionsJPanel", lenderFuntionsJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnLenderFunctionsActionPerformed

    private void btnCreateBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAccountActionPerformed
        // TODO add your handling code here:
        LenderCreateBankAccountJPanel  lenderCreateBankAccountJPanel = new LenderCreateBankAccountJPanel(leftContainer, rightContainer, enterprise, userAccount, system);
        rightContainer.add("LenderCreateBankAccountJPanel", lenderCreateBankAccountJPanel );
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnCreateBankAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAccount;
    private javax.swing.JButton btnLenderFunctions;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
