/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Borrower;

import Business.BankAccount.BankAccount;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.LenderOrganisation;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ModeratorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author manas
 */
public class BorrowerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel rightContainer;
    private JPanel leftContainer;
    private UserAccount userAccount;
//    private BankAccount bankAccount;
    private LenderOrganisation  lenderOrganisation;
    private Enterprise enterprise;
    private Ecosystem system;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public BorrowerWorkAreaJPanel(JPanel leftContainer, JPanel rightContainer, Enterprise enterprise, UserAccount account, Ecosystem system) {
        initComponents();
         this.rightContainer= rightContainer;
         this.leftContainer=leftContainer;
         this.userAccount = account;
         this.enterprise = enterprise;
         this.system=system;
//         this.bankAccount = bankAccount;
         
         if(userAccount.getBankAccount().getName()== null){
             createBankAccountButton.setVisible(true);
             btnCheckApproval.setVisible(false);
             btnRepayLoan.setVisible(false);
             btnRequestFunds.setVisible(false);
             btnViewCreditHistory.setVisible(false);
             btnRepay.setVisible(false);
         }
         else{
             createBankAccountButton.setVisible(false);
             btnCheckApproval.setVisible(true);
             btnRepayLoan.setVisible(true);
             btnRequestFunds.setVisible(true);
             btnViewCreditHistory.setVisible(true);
             btnRepay.setVisible(true);
        }
         
//         
//         for(WorkRequest request: userAccount.getWorkQueue().getWorkRequestList() ){
//           if(request.getStatus().equals("Approved")){
//           
//              JOptionPane.showMessageDialog(null,"Your loan has been approved");
//           
//           }
//         
//         
//         }
    }
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRequestFunds = new javax.swing.JButton();
        btnCheckApproval = new javax.swing.JButton();
        btnViewCreditHistory = new javax.swing.JButton();
        btnRepayLoan = new javax.swing.JButton();
        createBankAccountButton = new javax.swing.JButton();
        btnRepay = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Borrower Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        btnRequestFunds.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRequestFunds.setText("Wallet");
        btnRequestFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestFundsActionPerformed(evt);
            }
        });
        add(btnRequestFunds, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 193, -1));

        btnCheckApproval.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCheckApproval.setText("Requests");
        btnCheckApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckApprovalActionPerformed(evt);
            }
        });
        add(btnCheckApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 193, -1));

        btnViewCreditHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewCreditHistory.setText("Update  Business Idea");
        btnViewCreditHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCreditHistoryActionPerformed(evt);
            }
        });
        add(btnViewCreditHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, -1));

        btnRepayLoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRepayLoan.setText("Manage Repayment");
        btnRepayLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepayLoanActionPerformed(evt);
            }
        });
        add(btnRepayLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 40));

        createBankAccountButton.setText("Create Bank Account");
        createBankAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBankAccountButtonActionPerformed(evt);
            }
        });
        add(createBankAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 30));

        btnRepay.setText("Repay Loan");
        btnRepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepayActionPerformed(evt);
            }
        });
        add(btnRepay, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestFundsActionPerformed
        // TODO add your handling code here:
       
        MyWallet myWallet=new  MyWallet(rightContainer,userAccount,enterprise,system);
        rightContainer.add("MyWalletJPanel",myWallet);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
       
        
        
    }//GEN-LAST:event_btnRequestFundsActionPerformed

    private void btnCheckApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckApprovalActionPerformed
        // TODO add your handling code here:
        
        CheckApprovalJPanel checkApprovalJPaenl = new CheckApprovalJPanel(rightContainer,userAccount,enterprise,system);
        rightContainer.add("CheckApprovalJPanel",checkApprovalJPaenl);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
       
    }//GEN-LAST:event_btnCheckApprovalActionPerformed

    private void createBankAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBankAccountButtonActionPerformed
        // TODO add your handling code here:
        CreateBankAccountJPanel createBankAccountJPanel = new CreateBankAccountJPanel(leftContainer,rightContainer,userAccount,enterprise,system);
        rightContainer.add("CreateBankAccountJPanel",createBankAccountJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_createBankAccountButtonActionPerformed


    private void btnRepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepayActionPerformed
        // TODO add your handling code here:
        RepaymentJPanel repaymentJPanel = new RepaymentJPanel(rightContainer,userAccount,enterprise,system);
        rightContainer.add("RepaymentJPanel",repaymentJPanel);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
    }//GEN-LAST:event_btnRepayActionPerformed

    private void btnViewCreditHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCreditHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCreditHistoryActionPerformed

    private void btnRepayLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepayLoanActionPerformed
        // TODO add your handling code here:
        
        ManageRepaymentLoan manageRepay=new ManageRepaymentLoan(rightContainer,userAccount,enterprise,system);
        rightContainer.add("ManageRepaymentLoan",manageRepay);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.next(rightContainer);
        
    }//GEN-LAST:event_btnRepayLoanActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckApproval;
    private javax.swing.JButton btnRepay;
    private javax.swing.JButton btnRepayLoan;
    private javax.swing.JButton btnRequestFunds;
    private javax.swing.JButton btnViewCreditHistory;
    private javax.swing.JButton createBankAccountButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
