/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Borrower;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organisation.BorrowerOrganisation;
import Business.Organisation.LenderOrganisation;
import Business.Organisation.ModeratorOrganisation;
import Business.Organisation.Organisation;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.WorkQueue.BorrowerLoanRepayRequest;
import Business.WorkQueue.ModeratorRequest;
import Business.WorkQueue.ModeratorWorkRequest;
import Business.WorkQueue.WorkRequest;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manas
 */
public class ManageRepaymentLoan extends javax.swing.JPanel {

    /**
     * Creates new form ManageRepaymentLoan
     */
    private JPanel rightContainer;
    private JPanel leftContainer;
    private UserAccount userAccount;
    private BorrowerOrganisation borrowerOrganisation;
    private Enterprise enterprise;
    private Ecosystem system;
    private ModeratorRequest mrequest;
    private UserAccount lenderAccount;

    ManageRepaymentLoan(JPanel rightContainer, UserAccount userAccount, Enterprise enterprise, Ecosystem system) {

        initComponents();

        this.rightContainer = rightContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system; //To change body of generated methods, choose Tools | Templates.
//        this.mrequest = mrequest;
        populateTable();

    }

    public void populateTable() {
        Organisation org = null;
        for (Organisation organisation : enterprise.getOrganisationDirectory().getOrganisationList()) {
            if (organisation instanceof ModeratorOrganisation) {
                org = organisation;
                break;
            }
        }
        if (org != null) {
            DefaultTableModel model = (DefaultTableModel) tblRepayment.getModel();

            model.setRowCount(0);
            for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                if (request instanceof ModeratorRequest) {
                    Object[] row = new Object[5];
                    row[0] = request;
                    row[1] = ((ModeratorRequest) request).getLoanAmount();
                    row[2] = ((ModeratorRequest) request).getLender1();
                    row[3] = ((ModeratorRequest) request).getDuration();
                    row[4] = ((ModeratorRequest) request).getPendingAmount();

                    model.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepayment = new javax.swing.JTable();
        btnRepay = new javax.swing.JButton();
        ProgressBar1 = new javax.swing.JProgressBar();
        textRepay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Repayment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 41, 422, 33));

        tblRepayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower", "Pending loan", "Lender", "Duration", "Pending Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRepayment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 900, 150));

        btnRepay.setText("Repay");
        btnRepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepayActionPerformed(evt);
            }
        });
        add(btnRepay, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        add(ProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 280, 30));

        textRepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRepayActionPerformed(evt);
            }
        });
        add(textRepay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 280, 30));

        jLabel2.setBackground(new java.awt.Color(204, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Please key in the value you want to pay");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 280, 30));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepayActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblRepayment.getSelectedRow();

        if (selectedRow < 0) {

            JOptionPane.showMessageDialog(null, "Select a row");
            return;
        }

        ModeratorRequest requ = (ModeratorRequest) tblRepayment.getValueAt(selectedRow,0);

        String textRepayAmount = textRepay.getText();
        

        if (textRepayAmount.isEmpty()) {
            System.out.println("Please enter a valid input");
            JOptionPane.showConfirmDialog(null, "Field can't be empty", "naughty", JOptionPane.CANCEL_OPTION);

        }
        int repay = Integer.parseInt(textRepayAmount);
        requ.setRepayAmount(repay);

//        BorrowerLoanRepayRequest borrowerRepayRequest = new BorrowerLoanRepayRequest();
//        borrowerRepayRequest.setSender(userAccount);
//        borrowerRepayRequest.setMessage("First Installment");
////        borrowerRepayRequest.setRemainingAmont(mrequest.getPendingAmount());
////        borrowerRepayRequest.setLenderName(mrequest.getLender1().getEmployee().getName());
//        System.out.println("UserInterface.Borrower.ManageRepaymentLoan.btnRepayActionPerformed()"+borrowerRepayRequest.getLenderName());
//        Organisation org = null;
//        for (Organisation organization : enterprise.getOrganisationDirectory().getOrganisationList()) {
//            if (organization instanceof BorrowerOrganisation) {
//                org = organization;
//                break;
//            }
//        }
//        if (org != null) {
//            org.getWorkQueue().getWorkRequestList().add(borrowerRepayRequest);
//            userAccount.getWorkQueue().getWorkRequestList().add(borrowerRepayRequest);
//        }

        JOptionPane.showMessageDialog(null, "Amount sent to bank");


    }//GEN-LAST:event_btnRepayActionPerformed

    private void textRepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRepayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRepayActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRepay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRepayment;
    private javax.swing.JTextField textRepay;
    // End of variables declaration//GEN-END:variables
}
